[workspace]

[package]
name = "gen-topo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "4.4.11", features = ["derive"] }
petname = "1.1.3"
rand = "0.8.5"
